/**
 * 首页内置智能体目录（与 index.html agents 数组保持一致）
 */
const BUILTIN_AGENTS = [
  {
    id: 1,
    name: '婚姻家事咨询',
    icon: '⚖️',
    tag: '民商事',
    status: 'online',
    subtitle: '面向律师与当事人',
    url: 'agent-family.html',
    desc: '覆盖离婚诉讼、财产分割、子女抚养、继承纠纷等家事法律问题，提供专业法律意见与策略建议。',
    features: ['离婚诉讼策略分析', '财产分割方案建议', '子女抚养权评估'],
    supportsFileUpload: false,
    appId: 'd861r2l4shhbm4fgiqi0',
    apiKeyHint: 'd863****',
    source: 'builtin',
  },
  {
    id: 2,
    name: '客户需求整理',
    icon: '📋',
    tag: '助手',
    status: 'beta',
    subtitle: '面向律师团队',
    url: 'agent-client.html',
    desc: '自动提炼客户沟通要点，结构化整理需求清单、优先级与跟进计划，让每一条诉求都有迹可循。',
    features: ['自动提炼沟通要点', '结构化需求清单', '优先级与跟进计划'],
    supportsFileUpload: true,
    appId: 'd7bmqs6lvndbkehl8om0',
    apiKeyHint: 'd7e8****',
    source: 'builtin',
  },
  {
    id: 7,
    name: '债权人资格审查及意见生成',
    icon: '🏦',
    tag: '破产',
    status: 'beta',
    subtitle: '面向破产管理人团队',
    url: 'agent-bankruptcy.html',
    desc: '上传债权人申报材料，智能完成主体资格与债权依据审查，分段展示分析过程与正式意见，并支持一键导出 Word 文档。',
    features: ['申报材料完整性审查', '债权主体与金额核验', '审查意见 Word 导出'],
    supportsFileUpload: true,
    appId: 'd5mqjsttb44mugrc8d5g',
    apiKeyHint: 'd8tq****',
    source: 'builtin',
  },
  {
    id: 6,
    name: '执行文书起草',
    icon: '📝',
    tag: '文书',
    status: 'online',
    subtitle: '面向诉讼与执行团队',
    url: 'agent-document.html',
    desc: '基于裁判文书与案情材料，辅助起草强制执行申请、财产保全、执行异议等执行类法律文书，支持附件上传解析。',
    features: ['强制执行申请书', '财产保全文书', '执行异议与复议'],
    supportsFileUpload: true,
    appId: 'd7jla7ulvnd51n8943t0',
    apiKeyHint: 'd86m****',
    source: 'builtin',
  },
  {
    id: 3,
    name: '国企投资合规咨询',
    icon: '🏛️',
    tag: '合规',
    status: 'online',
    subtitle: '面向国企法务',
    url: 'agent-compliance.html',
    desc: '聚焦国有企业对外投资合规要点，涵盖审批流程、资产保值、信息披露及监管政策解读，支持附件材料分析。',
    features: ['对外投资审批指引', '资产保值合规审查', '监管政策实时解读'],
    supportsFileUpload: true,
    appId: 'd89rse54shh8t6j2tgjg',
    apiKeyHint: 'd8a0****',
    source: 'builtin',
  },
  {
    id: 4,
    name: '制度审查',
    icon: '🔍',
    tag: '合规',
    status: 'beta',
    subtitle: '面向企业合规团队',
    url: 'http://hiagent.aigc.smdata.com.cn/product/llm/chat/d85hgql4shh7i6sjdvjg',
    desc: '对企业规章制度、合同范本及内部流程进行合法性与合规性审查，识别潜在风险条款并提出修改意见。',
    features: ['规章制度合法性审查', '合同范本风险识别', '流程合规优化建议'],
    supportsFileUpload: false,
    external: true,
    source: 'builtin',
  },
  {
    id: 5,
    name: '税务咨询',
    icon: '🧾',
    tag: '税务',
    status: 'online',
    subtitle: '面向企业财务法务',
    url: 'agent-tax.html',
    desc: '涵盖企业所得税、增值税、个税筹划及税务稽查应对，结合最新政策给出合法节税方案。',
    features: ['企业所得税筹划', '增值税合规分析', '税务稽查应对策略'],
    supportsFileUpload: false,
    appId: 'd6sb35mlvnd51n87i510',
    apiKeyHint: 'd865****',
    source: 'builtin',
  },
  {
    id: 8,
    name: '私募股权投资基金',
    icon: '💼',
    tag: '投资',
    status: 'online',
    subtitle: '面向基金管理人及法务',
    url: 'agent-pefund.html',
    desc: '聚焦私募股权基金设立备案、合格投资者认定、GP/LP 治理结构及投资协议条款审查，提供募集合规与交易结构分析支持。',
    features: ['基金设立与备案指引', '合格投资者合规审查', '投资协议条款分析'],
    supportsFileUpload: false,
    appId: 'd82jt8l4shhes124k3cg',
    apiKeyHint: 'd876****',
    source: 'builtin',
  },
];

function listBuiltinAgents() {
  return BUILTIN_AGENTS.map(a => ({ ...a }));
}

module.exports = { listBuiltinAgents, BUILTIN_AGENTS };
